name: build_and_push_to_manifest
on:
  push:
    branches:
      - '*'
    # tags:
    #   - '*.*.*'
  pull_request:
  workflow_dispatch:
env:
  GITLAB_REGISTRY: registry.gitlab.com
  GITLAB_IMAGE_NAME: aamir454/bookinfo-project

  
jobs:

  docker:
    runs-on: aamir-runner
    steps:
      -
        name: Login to registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build docker image
        run: |
          docker build -f Dockerfile -t aamir454/bookinfo-project:${GITHUB_SHA::8} .
      - name: Push image to gitlab registry
        run: |
          docker push aamir454/bookinfo-project:${GITHUB_SHA::8}
          
  push_to_manifest:
    runs-on: ubuntu-latest
    name: push to manifest
    needs:
      - build_and_push_image
    steps:
      - name: Checkout manifest repo
        uses: actions/checkout@v2
        with:
          repository: tespkg/tes_manifests
          token: ${{ secrets.TES_MANIFEST_TOKEN }}

      - name: Set up tools
        uses: tespkg/action@set_up_tools

      - name: Push to dev
        ## your main branch
        ## push the image name to env-dev/${{ github.repository }}
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: tespkg/action@deploy_to_dev
        with:
          ALIAS_GITHUB_REPOSITORY: ${{ github.repository }}
          TES_ENV: dev
