name: build_and_push_to_manifest
env:
  GITLAB_REGISTRY: aamir454/bookinfo-project
  REPOSITORY_NAME: maven
  ARGOCD_REPO_NAME: pakdevops/maven
  NS: dev-deployment
  CI_REGISTRY_IMAGE: maven
  GITLAB_IMAGE_NAME: 'aamir454/bookinfo-project:${GITHUB_SHA::8}'
on:
  push:
    branches:
      - 'main'

jobs:
  build_and_push_image:
    runs-on: devops-pak
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      -
        name: Login to registry
        uses: actions/checkout@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build docker image
        run: |
          docker build -f Dockerfile -t aamir454/bookinfo-project:${GITHUB_SHA::8} .
      - name: Push image to gitlab registry
        run: |
          docker push aamir454/bookinfo-project:${GITHUB_SHA::8}

  deploy_to_dev:
    runs-on: devops-pak
    needs:
      - build_and_push_image
    steps:
      - name: Display the repository name
        run: echo "$REPOSITORY_NAME , $ARGOCD_REPO_NAME"
        shell: bash

      - name: Setup User and email for GIT next push
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name ${{ github.actor }}
          git config -l

      - name: Display the current folders
        run: |
          pwd
          ls

      - name: Clone Deployment Manifests Repo
        uses: actions/checkout@v2
        with:
          repository: pakdevops/manifests
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          path: manifests
      - name: Update Images via yq
        shell: bash
        run: |
#          sudo wget https://github.com/mikefarah/yq/releases/download/3.4.1/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq
          ls
          pwd
          MAIN_REPO=$(pwd)
          cd $MAIN_REPO
          cd manifests/dev-env/maven
          echo "list current common*.image.repository"
          yq r --printMode pv values.yaml "common*.image.repository"
          echo "latest GITLAB_IMAGE_NAME is aamir454/bookinfo-project"
          yq w -i values.yaml common*.image.repository aamir454/bookinfo-project
          yq r --printMode pv values.yaml "common*.image.repository"

          echo "list current common*.image.tag"
          yq r --printMode pv values.yaml "common*.image.tag"
          echo "latest GITLAB_IMAGE_TAG is ${GITHUB_SHA::8}"
          yq w -i values.yaml "common*.image.tag" ${GITHUB_SHA::8}
          yq r --printMode pv values.yaml "common*.image.tag"

      - name: Push manifests changes to ArgoCD's manifest repo
        run: |
          cd manifests
          git config user.name ${GITHUB_ACTOR}
          git config user.email ${GITHUB_ACTOR}@github.com
          git diff
          git add .
          git commit -m "${GITHUB_REPOSITORY}_${GITHUB_JOB}_${GITHUB_SHA:0:7}_details:${CI_COMMIT_MESSAGE}"
          git push
#  deploy_to_test:
#    runs-on: devops-pak
#    needs:
#      - deploy_to_dev
#    steps:
#      - name: TO DO
#        run: echo "Deploy to test server to-do"
#        shell: bash
#
