name: push helm chart

env:
  GITLAB_REGISTRY: aamir454/bookinfo-project
  DEFAULT_MOULE: true ## true, ingore, default is true
  SECOND_MODULE: 'null' ## null, ignore, ${MODULE_NAME},  default is null
  SECOND_MODULE_FOR_COMMON: 'common2 common3'
  THIRD_MODULE: ignore
  THIRD_MODULE_FOR_COMMON: 'common4 common5'
  # TES_MANIFEST_TEMPOARAY: ${{ secrets.TES_MANIFEST_TEMPOARAY }}
  ALIAS_GITHUB_REPOSITORY: ${{ github.repository }}
  HELM_REPO: http://charts.fiberdoctor.pk:8080/
  HELM_USER: ${{ secrets.HELM_USER }}
  HELM_PASSWORD: ${{ secrets.HELM_PASSWORD }}
  TES_ENV: dev

on:
  push:
    tags:
      - '*.*.*'

jobs:
  tag_image:
    runs-on: devops-pak
    name: tag and push image
    if: contains(github.ref, 'refs/tags/')
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
#      - id: tag_image
        name: Login to registry
        uses: actions/checkout@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
        name: Tag and Push image to gitlab registry
        run: |
#         IMAGE_TAG=`echo ${GITHUB_REF} | awk -F "/" '{print $3}'`
#         if [[ ${IMAGE_TAG} == v* ]]; then IMAGE_TAG=`echo ${IMAGE_TAG:1}`; fi
#         echo ${IMAGE_TAG}
#
#         if [ "$DEFAULT_MOULE" != "ignore" ] ;
#         then
            docker pull aamir454/bookinfo-project:${GITHUB_SHA::8}
            docker tag aamir454/bookinfo-project:${GITHUB_SHA::8} aamir454/bookinfo-project:${IMAGE_TAG}
            docker tag aamir454/bookinfo-project:${GITHUB_SHA::8} aamir454/bookinfo-project:latest
            docker push aamir454/bookinfo-project
            docker push aamir454/bookinfo-project:${IMAGE_TAG}
#          fi

  push_chart_to_helm_repo:
    runs-on: devops-pak
    name: push chart to helm repo
    if: contains(github.ref, 'refs/tags/')
    needs:
      - tag_image
    steps:
      - name: Checkout source repo
        if: contains(github.ref, 'mixedmanual')
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get branch Name
        if: contains(github.ref, 'mixedmanual')
        run: |
          git log --oneline --decorate | head -1
          BRANCH_NAME=`git log --oneline --decorate | head -1 | awk -Forigin/ '{print $2}' | awk -F')' '{print $1}'`
          echo "BRANCH_NAME: ${BRANCH_NAME}"
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV

      - name: Checkout manifest repo
        uses: actions/checkout@v2
        with:
          repository: pakdevops/manifests
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Set up tools
        uses: pakdevops/action@set_up_tools

      - name: push_incubator_chart
        uses: pakdevops/action@push_incubator_chart
        with:
          ALIAS_GITHUB_REPOSITORY: ${{ github.repository }}

  sync_helm_chart_to_env:
    runs-on: devops-pak
    name: sync helm chart to env
    if: contains(github.ref, 'refs/tags/')
    needs:
      - push_chart_to_helm_repo
    steps:
      - name: Checkout manifest repo
        uses: actions/checkout@v2
        with:
          repository: pakdevops/manifests
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      # - name: Set up tools
      #   uses: tespkg/action@set_up_tools

      - name: auto sync to env-test
        uses: pakdevops/action@sync_helm_chart
        with:
          ALIAS_GITHUB_REPOSITORY: ${{ github.repository }}
          TES_ENV: test
#       - name: auto sync to env-test2
#         uses: tespkg/action@sync_helm_chart
#         with:
#           ALIAS_GITHUB_REPOSITORY: ${{ github.repository }}
#           TES_ENV: test2
