name: push helm chart
env:
  IMAGE_REGISTRY_REPO: aamir454/bookinfo-project
  HELM_REPO: helm-charts
  HELM-URL: http://charts.fiberdoctor.pk:8080/
  HELM_USER: ${{ secrets.HELM_USER }}
  HELM_PASSWORD: ${{ secrets.HELM_PASSWORD }}
  APP-NAME: site1
on:
  push:
    tags:
      - '*.*.*'

jobs:
  tag_image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to registry
        uses: actions/checkout@v2.4.2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: image tag
        run: |
          docker tag $IMAGE_REGISTRY_REPO:${GITHUB_SHA::8} $IMAGE_REGISTRY_REPO:${GITHUB_REF_NAME} 
      - name: Push image to gitlab registry
        run: |
          docker push $IMAGE_REGISTRY_REPO:${GITHUB_REF_NAME}
          
    
  helm_push:
    runs-on: ubuntu-latest
    needs: tag_image
    steps:
      - name: Clone Deployment Manifests Repo
        uses: actions/checkout@v2.4.2
        with:
          repository: pakdevops/manifests
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          path: manifests
      - name: Update Images via yq
        shell: bash
        run: |
          ls
          cd manifests/test-env/site1
          ls
          export imagetag=${GITHUB_REF_NAME}
          echo $imagetag
          yq e -i '.image.tag = env(imagetag)' values-test.yaml
          yq e -i '.appVersion = env(imagetag)' Chart.yaml
          yq e -i '.version = env(imagetag)' Chart.yaml
          cat Chart.yaml
          cd ..
          ls
          echo ${GITHUB_REF_NAME}
          helm repo add helm-charts http://charts.fiberdoctor.pk:8080/
          helmv3 cm-push site1 helm-charts
          helm search repo helm-charts -l
      - name: Deploy to Test-Env
        run: |
          cd manifests
          git config user.name ${GITHUB_ACTOR}
          git config user.email ${GITHUB_ACTOR}@github.com
          git diff
          git add .
          git commit -m "${GITHUB_REPOSITORY}_${GITHUB_JOB}_${GITHUB_SHA:0:7}_details:${CI_COMMIT_MESSAGE}"
          git push
         
