name: push helm chart
env:
  IMAGE_REGISTRY_REPO: aamir454/bookinfo-project
  HELM_REPO: helm-charts
  HELM-URL: http://charts.fiberdoctor.pk:8080/
  HELM_USER: ${{ secrets.HELM_USER }}
  HELM_PASSWORD: ${{ secrets.HELM_PASSWORD }}
  APP-NAME: site1
on:
  push:
    tags:
      - '*.*.*'

jobs:
  tag_image:
    runs-on: devops-pak
    steps:
      - name: Login to registry
        uses: actions/checkout@v2.4.2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: image tag
        run: |
          docker pull $IMAGE_REGISTRY_REPO:7f36db8c
          docker tag $IMAGE_REGISTRY_REPO:7f36db8c $IMAGE_REGISTRY_REPO:${GITHUB_REF_NAME} 
      - name: Push image to gitlab registry
        run: |
          docker push $IMAGE_REGISTRY_REPO:${GITHUB_REF_NAME}
          
    
  helm_push:
    runs-on: devops-pak
    steps:
      - name: Clone Deployment Manifests Repo
        uses: actions/checkout@v2.4.2
        with:
          repository: pakdevops/manifests
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          path: manifests
      - name: Update Images via yq
        shell: bash
        run: |
          ls
          cd manifests/test-env/site1
          ls
          export imagetag=${GITHUB_REF_NAME}
          echo $imagetag
          yq e -i '.image.tag = env(imagetag)' values-test.yaml
          yq e -i '.appVersion = env(imagetag)' Chart.yaml
          yq e -i '.version = env(imagetag)' Chart.yaml
          yq e -i '.name = site1' Chart.yaml
          cat Chart.yaml
          cd ..
          ls
          echo ${GITHUB_REF_NAME}
          helm repo add $HELM_REPO $HELM-URL
          helmv3 cm-push $APP-NAME $HELM_REPO
          helm search repo $HELM_REPO -l
         
