name: push helm chart

on:
  push:
    tags:
      - '*.*.*'

jobs:
  tag image:
    runs-on: devops-pak
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      -
        name: Login to registry
        uses: actions/checkout@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: image tag
        run: |
          docker pull aamir454/bookinfo-project:7f36db8c
          docker tag aamir454/bookinfo-project:7f36db8c aamir454/bookinfo-project:${GITHUB_REF_NAME} 
      - name: Push image to gitlab registry
        run: |
          docker push aamir454/bookinfo-project:${GITHUB_REF_NAME}
          
    
  helm push:
    runs-on: devops-pak
    steps:
      - name: Clone Deployment Manifests Repo
        uses: actions/checkout@v2
        with:
          repository: pakdevops/manifests
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          path: manifests
      - name: Update Images via yq
        shell: bash
        run: |
          ls
          cd manifests/test-env/site1
          ls
          export imagetag=${GITHUB_REF_NAME}
          echo $imagetag
          yq e -i '.image.tag = env(imagetag)' values-test.yaml
          yq e -i '.appVersion = env(imagetag)' Chart.yaml
          yq e -i '.version = env(imagetag)' Chart.yaml
          cat values.yaml
          cd ..
          ls
          echo ${GITHUB_REF_NAME}
          helm cm-push site1/ --version=${GITHUB_REF_NAME} helm-charts
